/**
 * Temporary stub for v0 preview / Next.js.
 *
 * The real file is auto-generated by the Convex CLI (`npx convex dev`)
 * and provides fully-typed helpers for calling Convex functions.
 *
 * During preview we only need the named export `api` so that imports
 * like:
 *   import { api } from 'convex/_generated/api';
 * do not break the build.
 *
 * ⚠️  This file will be replaced by Convex’s code-gen in local
 *     development or production CI pipelines.
 */

export const api = {} as Record<string, unknown>
